import "./globals.scss";

import Header from "@/UI/Header/Header";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";


const roboto = Roboto({ weight: "100", subsets: ["cyrillic"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

type Props = {
    children: React.ReactNode
}

export default function RootLayout({children}: Props) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <Header>
                    {children}
                </Header>
            </body>
        </html>
    )
}
